name: Scrape Products Every 45 Minutes

on:
  schedule:
    - cron: "*/45 * * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Google Cloud credentials
      run: |
        echo "${{ secrets.FIREBASE_CREDENTIALS }}" > ./firebase-credentials.json
        ls -la  # Debugging Schritt
        head -n 5 firebase-credentials.json  # Überprüfe die ersten Zeilen der Datei

    - name: Run Scraping Script
      run: |
        python scraper.py

    - name: Clean up
      run: rm -f ./firebase-credentials.json
