name: Scrape Products and Update Firestore

on:
  workflow_dispatch: # Ermöglicht das manuelle Starten der Action
  schedule:
    - cron: '0 0 * * *' # Täglich um Mitternacht UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Inject Firebase credentials
      - name: Set up Firebase credentials
        run: echo "${{ secrets.FIREBASE_CREDENTIALS }}" > firebase-credentials.json

      # Run the Python script
      - name: Run scraper
        env:
          GOOGLE_APPLICATION_CREDENTIALS: firebase-credentials.json
        run: python scraper.py
